[INFO 15:14:23] pymarl Running command 'my_main'
[INFO 15:14:23] pymarl Started run with ID "87"
[DEBUG 15:14:23] pymarl Starting Heartbeat
[DEBUG 15:14:23] my_main Started
[INFO 15:14:23] my_main Experiment Parameters:
[INFO 15:14:23] my_main 

{   'agent': 'rnn',
    'batch_size': 1024,
    'batch_size_run': 32,
    'buffer_cpu_only': True,
    'buffer_size': 32,
    'checkpoint_path': '',
    'critic_lr': 0.0005,
    'cur_episodes': 32,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'heuristic_rest': False,
                    'map_name': '1c3s5z',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': None,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'episodes_per_teammate': 64,
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'exp_name': 'stage1_SC2',
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'ind': 'stage1',
    'inner_loop_episodes': 128,
    'label': 'default_label',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'local_saves_path': 'saves',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic',
    'meta_update_times': 1,
    'n_sub_modules': 3,
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimize_meta': True,
    'points_per_teammate': 64,
    'pop': 'stage1',
    'population_alg': 'vdn',
    'population_size': 5,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'runner': 'meta',
    'runner_log_interval': 10000,
    'save_BR': False,
    'save_BR_episodes': 2048,
    'save_model': False,
    'save_model_interval': 2000000,
    'save_population': True,
    'save_population_episodes': 4096,
    'save_replay': False,
    'seed': 414221581,
    't_max': 3000000,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'test_percent': 0.2,
    'train_test_split': False,
    'use_cuda': True,
    'use_history': False,
    'use_tensorboard': True,
    'z_dim': 64}

[INFO 15:14:28] my_main ================ MetaEpoch: 0 ================
[INFO 15:14:28] my_main Time passed: 0 seconds
[INFO 15:14:28] root [Individual 0] Begin training for 128 episodes
Process Process-3:
Process Process-1:
Process Process-2:
Process Process-4:
Process Process-5:
Process Process-6:
Process Process-7:
Process Process-8:
Process Process-9:
Process Process-10:
Process Process-11:
Process Process-12:
Process Process-13:
Process Process-14:
Process Process-15:
Process Process-16:
Process Process-17:
Process Process-18:
Process Process-19:
Process Process-20:
Process Process-21:
Process Process-22:
Process Process-23:
Process Process-24:
Process Process-25:
Process Process-26:
Process Process-27:
Process Process-28:
Process Process-29:
Process Process-30:
Process Process-32:
Process Process-31:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/code/src/runners/meta_runner.py", line 42, in env_worker
    env.reset()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 403, in reset
    self._launch()
  File "/home/cike/code/src/envs/starcraft2/starcraft2.py", line 318, in _launch
    self._run_config = run_configs.get(version=self.game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/__init__.py", line 36, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 175, in __init__
    super(Linux, self).__init__(base_dir, "SC2_x64", version=version, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 59, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 128, in __init__
    self.version = self._get_version(version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 236, in _get_version
    versions = self.get_versions(containing=game_version)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/pysc2/run_configs/platforms.py", line 90, in get_versions
    for v in os.listdir(versions_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cike/StarCraftII/Versions'
